fixes
oveeernight/functional-analysis pull request #6
Opened 2023-10-12 11:18 UTC by BUYT-1

2023-10-14 20:39 UTC, oveeernight requested changes

2023-10-14 20:39 UTC, oveeernight commented on src/02_metric_space.tex
> -    Мы так запаслись номерами, чтобы выражение было меньше $\varepsilon$
давай мы не будем вырезать поясняющие фразы лектора, я же их не сам придумываю)

2023-10-14 20:39 UTC, oveeernight commented on src/02_metric_space.tex
> +\begin{gather*}
multline*

2023-10-14 20:39 UTC, oveeernight commented on src/packages.tex
> +\usepackage{mathtools}
он уже есть в 6 строке

2023-10-14 20:39 UTC, oveeernight commented on src/02_metric_space.tex
> +    \[ p(\mathbb{0}) = 0 \land \forall x \in X p(x) \geq 0  \]
?)))))

2023-10-15 05:08 UTC, BUYT-1 commented on src/02_metric_space.tex
> +    \[ p(\mathbb{0}) = 0 \land \forall x \in X p(x) \geq 0  \]
Это просто чтобы читать комфортнее было.

2023-10-15 05:09 UTC, BUYT-1 commented on src/02_metric_space.tex
> -    Мы так запаслись номерами, чтобы выражение было меньше $\varepsilon$
Понять бы, что именно они поясняют. Если это не понятно сразу, то они только мешают.

2023-10-15 13:23 UTC, oveeernight commented on src/02_metric_space.tex
> +    \[ p(\mathbb{0}) = 0 \land \forall x \in X p(x) \geq 0  \]
не, не resolved. мне не то что бы жалко поменять условия местами. я нормально отношусь к изменениям, которые способствуют улучшению конспекта, но вот это уже просто вкусовщина. условие с квантором в начале никому хуже не делает. поэтому пусть будет так, как написал лектор.
 а мы сосредоточимся на более важных проблемах

2023-10-15 18:48 UTC, oveeernight commented on src/02_metric_space.tex
> -    Мы так запаслись номерами, чтобы выражение было меньше $\varepsilon$
давай мы не будем вырезать поясняющие фразы лектора, я же их не сам придумываю)

2023-10-15 18:53 UTC, BUYT-1 commented on src/02_metric_space.tex
> +    \[ p(\mathbb{0}) = 0 \land \forall x \in X p(x) \geq 0  \]
окей, маленькая деталь, не буду спорить

2023-10-16 17:55 UTC, merged