fixes 2
oveeernight/functional-analysis pull request #7
Opened 2023-10-24 17:13 UTC by BUYT-1

2023-10-26 17:14 UTC, oveeernight requested changes
Меня ОЧЕНЬ напрягает, что я захожу посмотреть, как было в лекции, и обнаруживаю, что ты исправил на то, как нравится тебе. Я не хочу каждую правку сверять с лекциеий. Если "правки" и дальше будут содержать примещуственно такой характер, я перестану смотреть PR-ы

2023-10-26 17:14 UTC, oveeernight commented on src/02_metric_space.tex
> +    \[n \in \bN \quad C^{(n)}[a,b] = \{ f | f: [a, b] \rightarrow \bR \land \exists f^{(n)} \in C[a,b] \} \]
я \exists и \forall окружаю `\,` не по приколу

2023-10-26 17:14 UTC, oveeernight commented on src/02_metric_space.tex
> +        l^\infty \coloneqq m(\bN)
![image](https://github.com/oveeernight/functional-analysis/assets/92212590/c2c3ad64-518e-42dd-8e7f-6adffc155e3a) ?
определение можно было написать получше, чем есть, но так оно только хуже стало)

2023-10-26 17:14 UTC, oveeernight commented on src/02_metric_space.tex
> +        \textcolor{red}{\forall \varepsilon > 0 \exists N \in \bN \forall m \in \bN \forall q \in \bN (m > N \land q > N) \Rightarrow} \normunder{f_m-f_q}{C^{(n)}} < \varepsilon \\
`\,` у кванторов я пишу, сам исправь в других местах тоже

2023-10-26 17:14 UTC, oveeernight commented on src/02_metric_space.tex
> +Последовательность~--- это функция на множестве натуральных чисел. Далее это используется явно.
реально было необходимо поменять то, что было, на то, что стало?

2023-10-26 17:14 UTC, oveeernight commented on src/02_metric_space.tex
> +    \[ \exists R > 0 \exists x_0 \in X A \subseteq B_R(x_0) \]
![image](https://github.com/oveeernight/functional-analysis/assets/92212590/d7b1ff4e-35dc-4e23-b086-1e9b448fab4a)
я правильно понимаю, что ты везде на \subseteq поменял, потому что тебе так больше нравится?)

2023-10-26 21:53 UTC, BUYT-1 commented on src/02_metric_space.tex
> +Последовательность~--- это функция на множестве натуральных чисел. Далее это используется явно.
А он определял как-то по-своему последовательность?
Просто в матане последовательность уже определялась как функция из натуральных чисел. Я, соответственно, просто адаптировал написанное к этому.

2023-10-26 22:03 UTC, BUYT-1 commented on src/02_metric_space.tex
> +        l^\infty \coloneqq m(\bN)
Вообще тут замысел такой. Я так понимаю, он хочет сказать, что l^\infty --- пространство ограниченных последовательностей. Но т.к. последовательность --- это функция из натуральных чисел, то получается, что l_^infty --- пространство ограниченных функций из натуральных чисел, множество которого как раз m(\bN).
Я тут забыл, что m(...) --- это только множество функций, так что надо определение метрики ещё сюда дописать, конечно + пояснение, что это дело есть пространство последовательностей --- предложения про "Далее это используется явно" может быть недостаточно.
Или я не так понял?

2023-10-26 22:08 UTC, BUYT-1 commented on src/02_metric_space.tex
> +        \textcolor{red}{\forall \varepsilon > 0 \exists N \in \bN \forall m \in \bN \forall q \in \bN (m > N \land q > N) \Rightarrow} \normunder{f_m-f_q}{C^{(n)}} < \varepsilon \\
Окей. Поменять в местах, где в прошлых ПРах это убрал? Тот же вопрос про \subseteq. Это не должно быть сложно.

2023-10-26 23:11 UTC, BUYT-1 commented on src/02_metric_space.tex
> +    \[ \exists R > 0 \exists x_0 \in X A \subseteq B_R(x_0) \]
Да. Раз уж это проблема, то вопрос: менять ли назад в других местах?

2023-10-29 08:23 UTC, oveeernight requested changes

2023-10-29 08:23 UTC, oveeernight commented on src/02_metric_space.tex
> +Последовательность~--- это функция на множестве натуральных чисел. Далее это используется явно.
я к тому что это выглядит как изменение ради изменения

2023-10-29 08:23 UTC, oveeernight commented on src/02_metric_space.tex
> +        l^\infty \coloneqq m(\bN)
я бы это определение поменял так: первые 3 строчки вынес перед ним, а замечание про полноту после. ну и там кринжово функция через underset была написана

2023-10-29 08:23 UTC, oveeernight commented on src/02_metric_space.tex
> +        \textcolor{red}{\forall \,  \varepsilon > 0 \exists N \in \bN \, \forall \, m \in \bN \, \forall \, q \in \bN (m > N \land q > N) \Rightarrow} \normunder{f_m-f_q}{C^{(n)}} < \varepsilon \\
отступы у \exists тоже

2023-10-29 08:23 UTC, oveeernight commented on src/02_metric_space.tex
> +     Из анализа известно, что $\forall \, x \in [a, b] \forall \, k \in (1\ldots n)\varphi_{k-1}'(x) = \varphi_{k}(x)$. Кроме того, $\forall \, m \in \bN f_m^{(n)}$ непрерывна на $[a, b]$ $\Rightarro
отступ перед квантором гораздо важнее отступа после (если он стоит не в самом начале формулы)

2023-10-31 08:21 UTC, BUYT-1 commented on src/02_metric_space.tex
> +Последовательность~--- это функция на множестве натуральных чисел. Далее это используется явно.
В оригинале было l_n^\infty = m(A), но вообще-то это равенство не соблюдается, кортежи длины n не являются функциями.
Здесь имелось в виду, что структура l_n^\infty такая же, как у m((1...n)), поэтому я пишу "можно думать как".

2023-10-31 08:32 UTC, BUYT-1 commented on src/02_metric_space.tex
> +        l^\infty \coloneqq m(\bN)
Получил пояснения от преподавателя --- он так пишет, потому что когда он использовал формальное определение последовательности (ф-я из натуральных) и говорил, что l^\infty = m(\bN) (пространство огр. ф-й из натуральных), люди не понимали, что это то же самое, что и пространство ограниченных последовательностей.
Я думаю, с напоминанием, что последовательность --- вообще-то такая функция, вопросов это определение не вызовет.
В текущем виде в определении много лишнего, что чела, который за неделю до экзамена будет читать этот док, задержит зазря на нём, чего не хочется (говорю по опыту).

2023-11-04 08:49 UTC, closed without merging

2023-11-04 09:07 UTC, BUYT-1 commented
? Я ж объяснил, почему сделал изменения.

2023-11-04 13:38 UTC, oveeernight commented
Делай свой форк со своими fixes, я не против, мне PR-ы кидать не надо

2023-11-04 14:09 UTC, BUYT-1 commented
Окей